### ISSUE TITLE
Backspace functionality changed

### ISSUE THREAD

**Issue by Jakejamesreid** [epilogic-ch/ice#8]
Just upgraded to the latest version from version 5.0 and it seems as though the backspace functionality has changed. When deleting text that spans over multiple p tags, they are all merged under one p tag. This throws off the formatting as line breaks are lost. Is there a way to prevent p tags from being merged?

So say for example I had the following:
![image](https://user-images.githubusercontent.com/27356828/118293396-848e1280-b4d1-11eb-8a87-5de8c81448fb.png)

Before when selecting those 2 p tags and pressing backspace I would get the following:
![image](https://user-images.githubusercontent.com/27356828/118293424-8c4db700-b4d1-11eb-838a-20847569fee7.png)

Now I get this:
![image](https://user-images.githubusercontent.com/27356828/118293445-9374c500-b4d1-11eb-96a6-6cc58aa561c0.png)

This renders as:
This is my textThis is some more text

As opposed to:
This is my text
This is some more text

Any help on how to solve this issue would be much appreciated.

TinyMCE V5.8

*Update:* So it seems that the initialsation functionality of the plugin is broken. I have set mergeBlocks to false but the settings are not taking place, neither are the custom paste commands I have created
![image](https://user-images.githubusercontent.com/27356828/118296627-18ada900-b4d5-11eb-9b99-40ec29ed005a.png)

**Comment by Jakejamesreid** [comment]
This issue was due to some exceptions being thrown during initialisation of the plugin. To fix this I had to get the non-minified plugin.js file from the github repo and change all occurrences of:
ed.addButton to ed.ui.registry.addButton
ed.addMenuItem to ed.ui.registry.addMenuItem

**Comment by morbac** [comment]
Thanks for your message.
If you send a pull request, I can merge into the project. However for backward compatibility it would be safe to add a test, somethink like:
`(ed.ui.registry.addButton ? ed.ui.registry.addButton : ed.addButton)`
`(ed.ui.registry.addMenuItem ? ed.ui.registry.addMenuItem : ed.addMenuItem)`

**Comment by Jakejamesreid** [comment]
> Thanks for your message.
> If you send a pull request, I can merge into the project. However for backward compatibility it would be safe to add a test, somethink like:
> `(ed.ui.registry.addButton ? ed.ui.registry.addButton : ed.addButton)`
> `(ed.ui.registry.addMenuItem ? ed.ui.registry.addMenuItem : ed.addMenuItem)`

Would love to help but I don't know how I could update your source code. The file that needs to be updated is minified.so I don't know how I can make the changes. If you let me know I would be happy to make the updates
